--------------------------------------------------------Product Analysis-------------------------------------------------------

--1.What is the most common payment method?
SELECT payment_method,
count(payment_method) as payment_method
FROM [dbo].[WalmartSQL repository.]
GROUP BY payment_method

--2.What is the total revenue generated by each product line?
SELECT product_line, 
SUM(total) as rev_generated
FROM [dbo].[WalmartSQL repository.]
GROUP BY product_line
ORDER BY SUM(total) DESC

--3.Which product line has the highest quantity sold?
SELECT TOP 1 product_line,
SUM(quantity) as quantity_sold
FROM [dbo].[WalmartSQL repository.]
GROUP BY product_line
ORDER BY SUM(quantity) DESC

--4.Which product line generates the highest average gross income?
SELECT TOP 1 product_line,
avg(gross_income) as avg_gross_income
FROM [dbo].[WalmartSQL repository.]
GROUP BY product_line
ORDER BY avg(gross_income) DESC

--5.What is the average rating for each product line — which one is rated highest/lowest?
SELECT product_line, avg_rating,
       CASE WHEN rnk_high = 1 THEN 'Highest' ELSE 'Lowest' END as label
FROM (
    SELECT product_line, avg_rating,
           RANK() OVER (ORDER BY avg_rating DESC) as rnk_high,
           RANK() OVER (ORDER BY avg_rating ASC) as rnk_low
    FROM (
        SELECT product_line, AVG(rating) as avg_rating
        FROM [dbo].[WalmartSQL repository.]
        GROUP BY product_line
    ) t
) ranked
WHERE rnk_high = 1 OR rnk_low = 1

--6.What is the Average Order Value (AOV) by branch and by customer type — and does AOV differ meaningfully between Member and Normal customers?
SELECT branch,customer_type,AVG(total) as aov,SUM(total) as total_rev
FROM [dbo].[WalmartSQL repository.]
GROUP BY branch,customer_type
order by branch 

--7.What is the Gross Merchandise Value (GMV) contributed by each product line?
SELECT product_line, SUM(total)
FROM [dbo].[WalmartSQL repository.]
GROUP BY product_line 
ORDER BY SUM(total) DESC 

--8.Does Average Order Value vary by time of day or day of week — are customers spending more per transaction during specific hours/days?
SELECT time_of_day,'Time of Day' as dimension,AVG(total)as aov, count(*)
FROM [dbo].[WalmartSQL repository.]
GROUP BY time_of_day
UNION ALL
SELECT day_name,'Day of Week' as dimension,AVG(total) as aov, count(*)
FROM [dbo].[WalmartSQL repository.]
GROUP BY day_name
ORDER BY dimension, aov DESC
